config/routes.rb
Rails.application.routes.draw do

  get 'subsections/:id/destroy' => 'subsections#destroy', as: :subsection_destroy
  resources :subsections
  
  get 'sections/:id/destroy' => 'sections#destroy', as: :section_destroy
  resources :sections

  get 'biznesstypes/get_biznesstype'

  get 'catalogs/:catalog_id/particles/:particle_id/items/:id/destroy' => 'items#destroy', as: :catalog_particle_item_destroy
  get 'catalogs/:catalog_id/particles/:id/destroy' => 'particles#destroy', as: :catalog_particle_destroy
  put 'catalogs/:id/setcoordinate' => 'catalogs#setcoordinate', as: :catalog_setcoordinate
  get 'catalogs/:id/mappopup' => 'catalogs#mappopup', as: :catalog_mappopup
  get 'catalogs/:id/destroy' => 'catalogs#destroy', as: :catalog_destroy
  resources :catalogs do
    resources :particles do
      resources :items
    end
  end

  get 'localities/get_locality'

  get 'home/index' => 'home#index', as: :home

  get 'admpanel/index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get 'users/password_recovery'
  post 'users/password_send'
  get 'users/registration'
  post 'users/registration' => 'users#create', as: :user_create
  get 'users/registration_confirm'
  post 'users/registration_confirm' => 'users#regconfirm', as: :user_reg_confirm
  resources :users

  get 'welcome/index'
  root 'welcome#index'

end

app/models/subsection.rb
class Subsection < ActiveRecord::Base
  belongs_to :section
  validates :name, presence: true
  validates :section_id, presence: true
end

app/controllers/subsections_controller.rb
class SubsectionsController < ApplicationController
  before_action :set_subsection, only: [:show, :edit, :update, :destroy]

  # GET /subsections
  # GET /subsections.json
  def index
    @subsections = Subsection.all
  end

  # GET /subsections/1
  # GET /subsections/1.json
  def show
  end

  # GET /subsections/new
  def new
    @subsection = Subsection.new
  end

  # GET /subsections/1/edit
  def edit
  end

  # POST /subsections
  # POST /subsections.json
  def create
    @subsection = Subsection.new(subsection_params)

    respond_to do |format|
      if @subsection.save
        format.html { redirect_to @subsection, notice: 'Subsection was successfully created.' }
        format.json { render :show, status: :created, location: @subsection }
      else
        format.html { render :new }
        format.json { render json: @subsection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subsections/1
  # PATCH/PUT /subsections/1.json
  def update
    respond_to do |format|
      if @subsection.update(subsection_params)
        format.html { redirect_to @subsection, notice: 'Subsection was successfully updated.' }
        format.json { render :show, status: :ok, location: @subsection }
      else
        format.html { render :edit }
        format.json { render json: @subsection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subsections/1
  # DELETE /subsections/1.json
  def destroy
    @subsection.destroy
    respond_to do |format|
      format.html { redirect_to subsections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subsection
      @subsection = Subsection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subsection_params
      params.require(:subsection).permit(:name, :section_id)
    end
end

app/helpers/subsections_helper.rb
module SubsectionsHelper
end

app/views/subsections/_form.html.erb
<%= form_for(@subsection) do |f| %>
  <% if @subsection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subsection.errors.count, "error") %> prohibited this subsection from being saved:</h2>

      <ul>
      <% @subsection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :section_id %><br>
    <%= f.select :section_id, options_from_collection_for_select( Section.all, "id", "name") %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subsections/edit.html.erb
<h1>Editing subsection</h1>

<%= render 'form' %>

<%= link_to 'Show', @subsection %> |
<%= link_to 'Back', subsections_path %>

app/views/subsections/index.html.erb
<h1>Listing subsections</h1>

<table>
  <thead>
    <tr>
      <th>Раздел</th>
      <th>Подраздел</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subsections.each do |subsection| %>
      <tr>
        <td><%= Section.find(subsection.section_id).name %></td>
        <td><%= subsection.name %></td>
        <td><%= link_to 'Show', subsection %></td>
        <td><%= link_to 'Edit', edit_subsection_path(subsection) %></td>
        <td><%= link_to 'Удалить', subsection_destroy_path(subsection) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subsection', new_subsection_path %>

app/views/subsections/new.html.erb
<h1>New subsection</h1>

<%= render 'form' %>

<%= link_to 'Back', subsections_path %>

app/views/subsections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subsection.name %>
</p>

<p>
  <strong>Section:</strong>
  <%= @subsection.section_id %>
</p>

<%= link_to 'Edit', edit_subsection_path(@subsection) %> |
<%= link_to 'Back', subsections_path %>