config/routes.rb
Rails.application.routes.draw do

  get 'subsections/:id/destroy' => 'subsections#destroy', as: :subsection_destroy
  resources :subsections
  
  get 'sections/:id/destroy' => 'sections#destroy', as: :section_destroy
  resources :sections

  get 'biznesstypes/get_biznesstype'

  get 'catalogs/:catalog_id/particles/:particle_id/items/:id/destroy' => 'items#destroy', as: :catalog_particle_item_destroy
  get 'catalogs/:catalog_id/particles/:id/destroy' => 'particles#destroy', as: :catalog_particle_destroy
  put 'catalogs/:id/setcoordinate' => 'catalogs#setcoordinate', as: :catalog_setcoordinate
  get 'catalogs/:id/mappopup' => 'catalogs#mappopup', as: :catalog_mappopup
  get 'catalogs/:id/destroy' => 'catalogs#destroy', as: :catalog_destroy
  resources :catalogs do
    resources :particles do
      resources :items
    end
  end

  get 'localities/get_locality'

  get 'home/index' => 'home#index', as: :home

  get 'admpanel/index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get 'users/password_recovery'
  post 'users/password_send'
  get 'users/registration'
  post 'users/registration' => 'users#create', as: :user_create
  get 'users/registration_confirm'
  post 'users/registration_confirm' => 'users#regconfirm', as: :user_reg_confirm
  resources :users

  get 'welcome/index'
  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  has_attached_file :avatar, 
                    :styles => { :medium => "300x300>", :thumb => "100x100>", :thumb1 => "177x177>" },
                    :path => ":rails_root/public/images/avatars/:id/:style/:basename.:extension",
                    :url  => "/images/avatars/:id/:style/:basename.:extension",
                    :default_url => "/images/avatar-missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.authenticate(login, password)
    user = find_by(phone: login)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else  
      nil
    end
  end

  has_many :catalogs, :dependent => :destroy
  #has_many :filters, :dependent => :destroy
  #has_many :presentations, :through => :catalogs
  #has_many :reviews, :dependent => :destroy

  # проверка на непустое поле
  validates :phone, presence: true
  validates :nick, presence: true
  validates :gender, presence: true
  validates :email, presence: true
  validates :locality, presence: true
  validates :password_open_text, presence: true
  validates :password_open_text, length: { in: 4..20 }

  # проверка на уникальность
  validates :phone, :uniqueness => true
  validates :unique_id, :uniqueness => true
  validates :email, :uniqueness => true
  validates :nick, :uniqueness => true

  def groupadd(group = '')
    groups = self.group + ',' + group
    self.update(group: groups)
  end

  def groupdel(group = '')
    groups = self.group
    groups = groups.gsub(/#{group}/,'')
    groups = groups.gsub(/(\,){2,}/,'')
    groups = groups.gsub(/\,$/,'')
    self.group = groups
    self.update(group: groups)
  end

  def groupcheck
    groups = self.group
    if groups.include? 'registered'
      groups = groups.gsub(/registered/,'newbie')
    end
    if groups[groups.size-1] == ','
      groups.chop! 
    end
    self.group = groups
    self.update(group: groups)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :mark

  def registration
    @user = User.new
  end

  def registration_confirm
    @user = User.find_by_id(marked_user.id)
  end

  def edit
    @user = User.find_by_id(marked_user.id)
  end

  def create
    @user = User.find_by_id(marked_user.id)
    @user.password = params[:user][:password_open_text]
    @user.group = 'registered'
    if @user.update(user_params)
      redirect_to users_registration_confirm_path
    else
      render 'registration'
    end
  end

  def regconfirm
    redirect_to home_path
  end

  def update
    @user = current_user
    unless params[:user][:password_open_text].nil?
      @user.password = params[:user][:password_open_text]
    end
    if @user.update(user_params)
      flash.now[:alert] = "Ваш профиль обновлён успешно"
      render 'edit'
    else
      render 'edit'
    end
  end

  def password_recovery
  end

  def password_send
    unless params[:phone].empty?
      @user = User.find_by_phone(params[:phone])
      if @user
        if Rails.env.development? 
          flash.now[:alert] = "Пароль отправлен по СМС #{@user.password_open_text}"
        else
          flash.now[:alert] = "Пароль отправлен по СМС"
        end
      else
        flash.now[:alert] = "Учётная запись для телефона #{params[:phone]} не найдена"
      end
    else
      unless params[:email].empty?
        @user = User.find_by_email(params[:email])
        if @user
          if Rails.env.development? 
            flash.now[:alert] = "Пароль отправлен по email: #{@user.email} #{@user.password_open_text}"
          else
            flash.now[:alert] = "Пароль отправлен на email: #{@user.email}"
          end
          PasswordRecoveryMailer.recovery_pwd(@user).deliver
        else
          flash.now[:alert] = "Учётная запись для email #{params[:email]} не найдена"
        end
      end
    end
    render 'password_recovery'
  end

  def show
    @user = User.find(params[:id])
    @catalog = @user.catalogs.first
    @pic = @catalog.catalogimgs.first
  end

private
  def user_params
    params.require(:user).permit( :phone, :password_open_text, :nick,
                                  :gender, :email, :locality, :birthday, :avatar )
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div id="form_page">
  <h3>Редактировнаие профиля пользователя «<%= current_user.nick %>»</h3>
  <%= form_for @user, :html => { :multipart => true } do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> при обновлении профиля:</h2>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <ul>
      <li><span>Псевдоним пользователя:</span>
          <%= f.text_field :nick %></li>
      <li><span>Населённый пункт:</span>
          <%= f.text_field :locality %></li>
      <li><span>Дата рождения:</span>
          <%= f.text_field :birthday %></li>
      <li id="sex">
          <span>Пол:</span>
          <%= f.radio_button :gender, "man" %> М | 
          <%= f.radio_button :gender, "woman" %> Ж
      </li>
      <li><span>Тел:</span>
          <%= f.text_field :phone %></li>
      <li><span>e-mail:</span>
          <%= f.text_field :email %></li>
      <li><span>Аватарка:<br>
          <%= image_tag @user.avatar.url(:thumb), :width => "55px" %></span>
          <%= f.file_field :avatar %>
      <li><span>Пароль:</span>
          <%= f.text_field :password_open_text %></li>
    </ul>
    <%= f.submit "Изменить данные", :id => "submit_but" %>
  <% end %>
</div>

<% content_for :head do %>
  <script src="/javascripts/jquery.ui.core.js"></script>
  <script src="/javascripts/jquery.ui.widget.js"></script>
  <script src="/javascripts/jquery.ui.position.js"></script>
  <script src="/javascripts/jquery.ui.menu.js"></script>
  <script src="/javascripts/jquery.ui.autocomplete.js"></script>
  <script src="/javascripts/jquery.ui.datepicker.js"></script>
  <script src="/javascripts/jquery.ui.datepicker-ru.js"></script>
  <script src="/javascripts/registration.js"></script>
<% end %>

app/views/users/password_recovery.html.erb
<div id="form_page">
  <h3>Восстановление пароля</h3>
  <p style="text-align: center">Для восстановления пароля заполните удобный способ восстановленя пароля и нажмите «Выслать пароль»</p>
  <%= form_tag(users_password_send_path) do %>
    <ul>
      <li><span>Телефон:</span>
          <%= text_field_tag :phone %></li>
      <li><span>e-mail</span>
          <%= text_field_tag :email %>
    </ul>
    <%= submit_tag "Выслать пароль", :id => "submit_but" %>
  <% end %>
</div>

app/views/users/registration.html.erb
<div id="form_page">
  <h3>Регистрация пользователя</h3>
  <%= form_for @user, :url => user_create_path, :html => { :multipart => true, :method => :post } do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> при регистрации пользователя</h2>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <ul>
      <li><span>Псевдоним пользователя:</span>
          <%= f.text_field :nick %></li>
      <li><span>Населённый пункт:</span>
          <%= f.text_field :locality %></li>
      <li><span>Дата рождения:</span>
          <%= f.text_field :birthday, :value => "2014-01-01" %></li>
      <li id="sex">
          <span>Пол:</span>
          <%= f.radio_button :gender, "man" %> М | 
          <%= f.radio_button :gender, "woman" %> Ж
      </li>
      <li><span>Тел:</span>
          <%= f.text_field :phone %></li>
      <li><span>e-mail:</span>
          <%= f.text_field :email %></li>
      <li><span>Аватарка:<br><%= image_tag @user.avatar.url(:thumb), :width => "55px" %></span>
      <%= f.file_field :avatar %>
    </ul>
    <%= f.submit "Зарегистрироваться", :id => "submit_but" %>
  <% end %>
</div>

<% content_for :head do %>
  <script src="/javascripts/jquery.ui.core.js"></script>
  <script src="/javascripts/jquery.ui.widget.js"></script>
  <script src="/javascripts/jquery.ui.position.js"></script>
  <script src="/javascripts/jquery.ui.menu.js"></script>
  <script src="/javascripts/jquery.ui.autocomplete.js"></script>
  <script src="/javascripts/jquery.ui.datepicker.js"></script>
  <script src="/javascripts/jquery.ui.datepicker-ru.js"></script>
  <script src="/javascripts/registration.js"></script>
<% end %>

app/views/users/registration_confirm.html.erb
<div id="form_page">
  <h3>Подтверждение Регистрации пользователя</h3>
  <%= form_for @user, :url => login_path, :html => { :method => :post } do |f| %>
  
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> при создании пользователя</h2>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    
    <ul>
      <li><span>Ваш номер телефона:</span>
          <%= text_field_tag :login, @user.phone %></li>
      <% if Rails.env.development? %>
        <li>пароль виден только в режиме разработки: <%= @user.password_open_text %></li>
      <% end %>
      <li><span>Пароль выслан Вам на СМС</span>
          <%= text_field_tag :password %>
    </ul>
    <%= f.submit "Зарегистрироваться", :id => "submit_but" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div id="home">
	<h3>Информация о пользователе <%= @user.nick %></h3>
	<div id="object_info">
		<div id="left_info">
			<div id="profile_info">
				<%= image_tag @user.avatar.url(:thumb) %>
				<a href="../user_logon/send_mess.html" class="button">Написать сообщение</a>
			</div>
			<div id="profile_info1">
				<ul id="object_info_ul">
					<li><span>Nik:</span> <%= @user.nick %></li>
					<li><span>Адрес:</span> <%= @user.locality %></li>
					<li><span>Дата регистрации:</span> <%= @user.created_at %></li>
				</ul>
			</div>
			<div id="my_cat">
				<a href="<%= catalog_path(@catalog) %>">
					<%= image_tag @pic.picture.url(:thumb) %>
					<%= @catalog.name %>
				</a>
			</div>
		</div>
	</div>
</div>