config/routes.rb
Rails.application.routes.draw do

  get 'subsections/:id/destroy' => 'subsections#destroy', as: :subsection_destroy
  resources :subsections
  
  get 'sections/:id/destroy' => 'sections#destroy', as: :section_destroy
  resources :sections

  get 'biznesstypes/get_biznesstype'

  get 'catalogs/:catalog_id/particles/:particle_id/items/:id/destroy' => 'items#destroy', as: :catalog_particle_item_destroy
  get 'catalogs/:catalog_id/particles/:id/destroy' => 'particles#destroy', as: :catalog_particle_destroy
  put 'catalogs/:id/setcoordinate' => 'catalogs#setcoordinate', as: :catalog_setcoordinate
  get 'catalogs/:id/mappopup' => 'catalogs#mappopup', as: :catalog_mappopup
  get 'catalogs/:id/destroy' => 'catalogs#destroy', as: :catalog_destroy
  resources :catalogs do
    resources :particles do
      resources :items
    end
  end

  get 'localities/get_locality'

  get 'home/index' => 'home#index', as: :home

  get 'admpanel/index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get 'users/password_recovery'
  post 'users/password_send'
  get 'users/registration'
  post 'users/registration' => 'users#create', as: :user_create
  get 'users/registration_confirm'
  post 'users/registration_confirm' => 'users#regconfirm', as: :user_reg_confirm
  resources :users

  get 'welcome/index'
  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :particle
  has_many :itemimgs, :dependent => :destroy
  accepts_nested_attributes_for :itemimgs, :allow_destroy => true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :mark
  before_action :authorize
  before_action :set_catalog, only: [:new, :edit, :update, :destroy]
  before_action :set_particle, only: [:new, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = @particle.items.new
    @item.save
    @itemimg = @item.itemimgs.new
    @itemimg.save
    redirect_to edit_catalog_particle_item_path(@catalog, @particle, @item)
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to catalog_particle_path(@catalog, @particle), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to catalog_particle_path(@catalog, @particle), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catalog
      @catalog = Catalog.find(params[:catalog_id])
    end

    def set_particle
      @particle = Particle.find(params[:particle_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :spec, itemimgs_attributes: [:picture, :id, :_destroy] )
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<% content_for :head do %>
  <script src="/javascripts/item_edit_form.js"></script>
<% end %>

<%= form_for(@item, url: catalog_particle_item_path(@catalog, @particle, @item), :html => { :multipart => true } ) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul>
    <li> <span>Заголовок предложения:</span> <%= f.text_field :name %> </li>
    <li> <span>Описание предложения:</span> <%= f.text_area :spec %> </li>
    <li> <h3>Фото</h3>
        <script type="text/javascript">
          var item_img_attr_counter = <%= @item.itemimgs.count %> ;
        </script>
         <table class="edit_table">
         <%= f.fields_for :itemimgs do |image| %>  
            <tr>
              <td> <%= image_tag image.object.picture.url(:thumb) %> </td>
              <td> Заменить:<br> <%= image.file_field :picture %>  </td>
              <td> Удалить<br><%= image.check_box :_destroy %> </td>
            </tr>
         <% end %>
         </table>
        <div id='add_itemimgs_block'>
        </div>
        <input type="button" id='add_itemimgs_link' value="Добавить ещё изображение" style="width: 200px">
    </li>
  </ul>
  <%= f.submit "Сохранить изменения", { :id => "submit_but" }  %>
<% end %>

app/views/items/edit.html.erb
<div id="form_page">
  <h3>Редактирование предложения «<%= @item.name %>» на странице «<%= @particle.name %>» каталога «<%= @catalog.name %>»</h3>
  <%= render 'form' %>
</div>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Spec</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.spec %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Spec:</strong>
  <%= @item.spec %>
</p>

<%= link_to 'Edit', edit_catalog_particle_item_path(1,1,@item) %> |
<%= link_to 'Back', catalog_particle_items_path(1,1,1) %>