config/routes.rb
Rails.application.routes.draw do

  get 'subsections/:id/destroy' => 'subsections#destroy', as: :subsection_destroy
  resources :subsections
  
  get 'sections/:id/destroy' => 'sections#destroy', as: :section_destroy
  resources :sections

  get 'biznesstypes/get_biznesstype'

  get 'catalogs/:catalog_id/particles/:particle_id/items/:id/destroy' => 'items#destroy', as: :catalog_particle_item_destroy
  get 'catalogs/:catalog_id/particles/:id/destroy' => 'particles#destroy', as: :catalog_particle_destroy
  put 'catalogs/:id/setcoordinate' => 'catalogs#setcoordinate', as: :catalog_setcoordinate
  get 'catalogs/:id/mappopup' => 'catalogs#mappopup', as: :catalog_mappopup
  get 'catalogs/:id/destroy' => 'catalogs#destroy', as: :catalog_destroy
  resources :catalogs do
    resources :particles do
      resources :items
    end
  end

  get 'localities/get_locality'

  get 'home/index' => 'home#index', as: :home

  get 'admpanel/index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get 'users/password_recovery'
  post 'users/password_send'
  get 'users/registration'
  post 'users/registration' => 'users#create', as: :user_create
  get 'users/registration_confirm'
  post 'users/registration_confirm' => 'users#regconfirm', as: :user_reg_confirm
  resources :users

  get 'welcome/index'
  root 'welcome#index'

end

app/models/biznesstype.rb
class Biznesstype < ActiveRecord::Base
end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  belongs_to :user
  serialize :sss
  #validates :name,:locality,:addr,:phone,:email,:description,:biztype, presence: true
  #validates :email, :format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, :message => ": неправильный формат" }
  has_many :catalogimgs, :dependent => :destroy
  accepts_nested_attributes_for :catalogimgs, :allow_destroy => true
  has_many :particles, :dependent => :destroy
end

app/models/catalogimg.rb
class Catalogimg < ActiveRecord::Base
  belongs_to :catalog
  has_attached_file :picture,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :path => ":rails_root/public/pics/catalogimgs/:id/:style/:basename.:extension",
                    :url  => "/pics/catalogimgs/:id/:style/:basename.:extension",
                    :default_url => "/images/avatar-missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :particle
  has_many :itemimgs, :dependent => :destroy
  accepts_nested_attributes_for :itemimgs, :allow_destroy => true
end

app/models/itemimg.rb
class Itemimg < ActiveRecord::Base
  belongs_to :item
  has_attached_file :picture,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :path => ":rails_root/public/pics/itemimgs/:id/:style/:basename.:extension",
                    :url  => "/pics/itemimgs/:id/:style/:basename.:extension",
                    :default_url => "/images/avatar-missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/itemimgs.rb
class Itemimgs < ActiveRecord::Base
  belongs_to :item
  has_attached_file :picture,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :path => ":rails_root/public/pics/catalogimgs/:id/:style/:basename.:extension",
                    :url  => "/pics/catalogimgs/:id/:style/:basename.:extension",
                    :default_url => "/images/avatar-missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/locality.rb
class Locality < ActiveRecord::Base
end

app/models/particle.rb
class Particle < ActiveRecord::Base
  belongs_to :catalog
  has_many :items, :dependent => :destroy
  accepts_nested_attributes_for :items, :allow_destroy => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :subsections, :dependent => :destroy
  validates :name, presence: true
  validates :name, :uniqueness => true
end

app/models/subsection.rb
class Subsection < ActiveRecord::Base
  belongs_to :section
  validates :name, presence: true
  validates :section_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  has_attached_file :avatar, 
                    :styles => { :medium => "300x300>", :thumb => "100x100>", :thumb1 => "177x177>" },
                    :path => ":rails_root/public/images/avatars/:id/:style/:basename.:extension",
                    :url  => "/images/avatars/:id/:style/:basename.:extension",
                    :default_url => "/images/avatar-missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.authenticate(login, password)
    user = find_by(phone: login)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else  
      nil
    end
  end

  has_many :catalogs, :dependent => :destroy
  #has_many :filters, :dependent => :destroy
  #has_many :presentations, :through => :catalogs
  #has_many :reviews, :dependent => :destroy

  # проверка на непустое поле
  validates :phone, presence: true
  validates :nick, presence: true
  validates :gender, presence: true
  validates :email, presence: true
  validates :locality, presence: true
  validates :password_open_text, presence: true
  validates :password_open_text, length: { in: 4..20 }

  # проверка на уникальность
  validates :phone, :uniqueness => true
  validates :unique_id, :uniqueness => true
  validates :email, :uniqueness => true
  validates :nick, :uniqueness => true

  def groupadd(group = '')
    groups = self.group + ',' + group
    self.update(group: groups)
  end

  def groupdel(group = '')
    groups = self.group
    groups = groups.gsub(/#{group}/,'')
    groups = groups.gsub(/(\,){2,}/,'')
    groups = groups.gsub(/\,$/,'')
    self.group = groups
    self.update(group: groups)
  end

  def groupcheck
    groups = self.group
    if groups.include? 'registered'
      groups = groups.gsub(/registered/,'newbie')
    end
    if groups[groups.size-1] == ','
      groups.chop! 
    end
    self.group = groups
    self.update(group: groups)
  end
  
end

app/controllers/particles_controller.rb
class ParticlesController < ApplicationController
  before_filter :mark
  before_action :authorize
  before_action :set_catalog, only: [:new, :create, :update, :edit, :show, :destroy]
  before_action :set_particle, only: [:update, :edit, :show, :destroy]

  def new
    @particle = @catalog.particles.new
    if @particle.save
      @item = @particle.items.new
      @item.save
      @itemimg = @item.itemimgs.new
      @itemimg.save
      redirect_to edit_catalog_particle_path(@catalog, @particle)
    else
      flash[:error] = "Страницу каталога создать не удалось!"
      redirect_to catalog_path(@catalog)
    end
  end

  def edit
  end

  def update
    if @particle.update(particle_params)
      flash[:notice] = "Страница каталога создана успешно."
      redirect_to catalog_path(@catalog)
    else
      flash[:error] = "Страницу каталога создать не удалось!"
      render :new
    end
  end

  def show

  end

  def destroy
    if @particle.destroy
      flash[:notice] = "Страница каталога удалена"
      redirect_to catalog_path(@catalog)
    else
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catalog
      @catalog = Catalog.find(params[:catalog_id])
    end

    def set_particle
      @particle = Particle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def particle_params
      params.require(:particle).permit( :id, :name, items_attributes: [:id, :name, :spec, itemimgs_attributes: [:id, :picture]] )
    end
end

app/helpers/admpanel_helper.rb
module AdmpanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/helpers/particles_helper.rb
module ParticlesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/particles/_form.html.erb
<%= form_for(@particle, url: catalog_particle_path(@catalog, @particle), :html => { :multipart => true } ) do |f| %>
  <% if @particle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@particle.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @particle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <ul>
    <li class="yellow_bg"> <span>Заголовок страницы:</span> <%= f.text_field :name %> </li>
    <hr>
    <%= f.fields_for :items do |item| %>
      <li> <span>Заголовок первого материала на странице:</span> <%= item.text_field :name %> </li>
      <li> <span>Описание первого материала на странице:</span> <%= item.text_area :spec %> </li>
      <%= item.fields_for :itemimgs do |img| %>
      <li>
        <span>Главное изображение:</span> <%= img.file_field :picture %><br>
      </li>
      <% end %>
    <% end %>
  </ul>
  <%= f.submit "Добавить", :id => "submit_but" %>
<% end %>

app/views/particles/edit.html.erb
<div id="form_page">
  <%= render 'form' %>
</div>

app/views/particles/new.html.erb
<div id="form_page">
<h3>Добавить страницу каталога «<%= @catalog.name %>»</h3>
  <%= render 'form' %>
</div>

app/views/particles/show.html.erb
<% content_for :head do %>
  <script type="text/javascript" src="/javascripts/galleria/galleria-1.3.5.min.js"></script>
  <script type="text/javascript" src="/javascripts/catalog_show.js"></script>
<% end %>

<div id="home" class="pages">
  <h1>
    <%= @particle.name %>
    <%= link_to "Добавить материал на страницу", new_catalog_particle_item_path(@catalog, @particle) %>
    <%= link_to "Удалить страницу", catalog_particle_destroy_path(@catalog, @particle) %>
  </h1>
  <div>
    <% @particle.items.each do | item | %>
      <h3>
        <%= item.name %>
        <%= link_to "Удалить", catalog_particle_item_destroy_path(@catalog, @particle, item) %>
        <%= link_to "Редактировать материал", edit_catalog_particle_item_path(@catalog, @particle, item) %>
      </h3>
      <div class="sobitie">
        <div class="info_sobitie">
          <div class="galleria">
            <% item.itemimgs.each do |iimg| %><br>
              <%= image_tag iimg.picture.url %><br>
            <% end %>
          </div>
          <p><%= item.spec.html_safe %></p>
        </div>
      </div>
      <img style="width: 120px" src="/images/soc_set.jpg">
    <% end %>
  </div>
<div>